### ISSUE TITLE
The program must not have two scripts, but one

### ISSUE THREAD

**Issue by duck-master** [rf20008/Character-Generator#1]
Currently, this repo contains _two_ scripts that do all of the program's logic: mine ([chargen-core.py](https://github.com/rf20008/Character-Generator/commit/aef6d3a058cb12c3bf5961b5ae9b9bc3b5ffc842#diff-274dbe08bafd12ab5d1720db9f055f03fb4d72bd53f9bc23b56dfbcf5b2ee73f)) and @rf20008's ([rf20008_gen_in_progress.py](https://github.com/rf20008/Character-Generator/commit/6becbf03c03e20713555aa52c83078702ee9d6b8#diff-bbb43005d23f3b3f1a0ef21955efc2eec7d500139233676374c50371f0f53d1e)). 

**We should decide on a single canonical script**, or otherwise merge the two scripts into a single file. (The scripts that we no longer need should be discarded from the current version of the repo, or at least deprecated with a prominent warning.) That way, debugging & testing will be many times easier, and end users will be just have a single, unified interface.

**Comment by rf20008** [comment]
We decided to use my script.

**Comment by duck-master** [comment]
There are now two scripts again. One of the scripts is called "rf20008 gen in progress.py", and the other is called "rf20008_gen_in_progress.py".

**Comment by rf20008** [comment]
it's fixed again :)
